// Generated by sprotodump. DO NOT EDIT!
// source: protoserver.lua

using System;
using Sproto;
using System.Collections.Generic;

namespace serverprotoType{ 
	public class drop : SprotoTypeBase {
		private static int max_field_count = 3;
		
		public class request : SprotoTypeBase {
			private static int max_field_count = 3;
			
			
			private Int64 _exp; // tag 0
			public Int64 exp {
				get { return _exp; }
				set { base.has_field.set_field (0, true); _exp = value; }
			}

			private Int64 _gold; // tag 1
			public Int64 gold {
				get { return _gold; }
				set { base.has_field.set_field (1, true); _gold = value; }
			}

			private List<titem> _items; // tag 2
			public List<titem> items {
				get { return _items; }
				set { base.has_field.set_field (2, true); _items = value; }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.exp = base.deserialize.read_integer ();
						break;
					case 1:
						this.gold = base.deserialize.read_integer ();
						break;
					case 2:
						this.items = base.deserialize.read_obj_list<titem> ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_integer (this.exp, 0);
				}

				if (base.has_field.has_field (1)) {
					base.serialize.write_integer (this.gold, 1);
				}

				if (base.has_field.has_field (2)) {
					base.serialize.write_obj (this.items, 2);
				}

				return base.serialize.close ();
			}
		}


		
		private Int64 _exp; // tag 0
		public Int64 exp {
			get { return _exp; }
			set { base.has_field.set_field (0, true); _exp = value; }
		}

		private Int64 _gold; // tag 1
		public Int64 gold {
			get { return _gold; }
			set { base.has_field.set_field (1, true); _gold = value; }
		}

		private List<titem> _items; // tag 2
		public List<titem> items {
			get { return _items; }
			set { base.has_field.set_field (2, true); _items = value; }
		}

		public drop () : base(max_field_count) {}

		public drop (byte[] buffer) : base(max_field_count, buffer) {
			this.decode ();
		}

		protected override void decode () {
			int tag = -1;
			while (-1 != (tag = base.deserialize.read_tag ())) {
				switch (tag) {
				case 0:
					this.exp = base.deserialize.read_integer ();
					break;
				case 1:
					this.gold = base.deserialize.read_integer ();
					break;
				case 2:
					this.items = base.deserialize.read_obj_list<titem> ();
					break;
				default:
					base.deserialize.read_unknow_data ();
					break;
				}
			}
		}

		public override int encode (SprotoStream stream) {
			base.serialize.open (stream);

			if (base.has_field.has_field (0)) {
				base.serialize.write_integer (this.exp, 0);
			}

			if (base.has_field.has_field (1)) {
				base.serialize.write_integer (this.gold, 1);
			}

			if (base.has_field.has_field (2)) {
				base.serialize.write_obj (this.items, 2);
			}

			return base.serialize.close ();
		}
	}


	public class package : SprotoTypeBase {
		private static int max_field_count = 2;
		
		
		private Int64 _type; // tag 0
		public Int64 type {
			get { return _type; }
			set { base.has_field.set_field (0, true); _type = value; }
		}

		private Int64 _session; // tag 1
		public Int64 session {
			get { return _session; }
			set { base.has_field.set_field (1, true); _session = value; }
		}

		public package () : base(max_field_count) {}

		public package (byte[] buffer) : base(max_field_count, buffer) {
			this.decode ();
		}

		protected override void decode () {
			int tag = -1;
			while (-1 != (tag = base.deserialize.read_tag ())) {
				switch (tag) {
				case 0:
					this.type = base.deserialize.read_integer ();
					break;
				case 1:
					this.session = base.deserialize.read_integer ();
					break;
				default:
					base.deserialize.read_unknow_data ();
					break;
				}
			}
		}

		public override int encode (SprotoStream stream) {
			base.serialize.open (stream);

			if (base.has_field.has_field (0)) {
				base.serialize.write_integer (this.type, 0);
			}

			if (base.has_field.has_field (1)) {
				base.serialize.write_integer (this.session, 1);
			}

			return base.serialize.close ();
		}
	}


	public class sysmessage : SprotoTypeBase {
		private static int max_field_count = 1;
		
		public class request : SprotoTypeBase {
			private static int max_field_count = 1;
			
			
			private string _msg; // tag 0
			public string msg {
				get { return _msg; }
				set { base.has_field.set_field (0, true); _msg = value; }
			}

			public request () : base(max_field_count) {}

			public request (byte[] buffer) : base(max_field_count, buffer) {
				this.decode ();
			}

			protected override void decode () {
				int tag = -1;
				while (-1 != (tag = base.deserialize.read_tag ())) {
					switch (tag) {
					case 0:
						this.msg = base.deserialize.read_string ();
						break;
					default:
						base.deserialize.read_unknow_data ();
						break;
					}
				}
			}

			public override int encode (SprotoStream stream) {
				base.serialize.open (stream);

				if (base.has_field.has_field (0)) {
					base.serialize.write_string (this.msg, 0);
				}

				return base.serialize.close ();
			}
		}


		
		private string _msg; // tag 0
		public string msg {
			get { return _msg; }
			set { base.has_field.set_field (0, true); _msg = value; }
		}

		public sysmessage () : base(max_field_count) {}

		public sysmessage (byte[] buffer) : base(max_field_count, buffer) {
			this.decode ();
		}

		protected override void decode () {
			int tag = -1;
			while (-1 != (tag = base.deserialize.read_tag ())) {
				switch (tag) {
				case 0:
					this.msg = base.deserialize.read_string ();
					break;
				default:
					base.deserialize.read_unknow_data ();
					break;
				}
			}
		}

		public override int encode (SprotoStream stream) {
			base.serialize.open (stream);

			if (base.has_field.has_field (0)) {
				base.serialize.write_string (this.msg, 0);
			}

			return base.serialize.close ();
		}
	}


	public class titem : SprotoTypeBase {
		private static int max_field_count = 3;
		
		
		private Int64 _id; // tag 0
		public Int64 id {
			get { return _id; }
			set { base.has_field.set_field (0, true); _id = value; }
		}

		private string _name; // tag 1
		public string name {
			get { return _name; }
			set { base.has_field.set_field (1, true); _name = value; }
		}

		private Int64 _count; // tag 2
		public Int64 count {
			get { return _count; }
			set { base.has_field.set_field (2, true); _count = value; }
		}

		public titem () : base(max_field_count) {}

		public titem (byte[] buffer) : base(max_field_count, buffer) {
			this.decode ();
		}

		protected override void decode () {
			int tag = -1;
			while (-1 != (tag = base.deserialize.read_tag ())) {
				switch (tag) {
				case 0:
					this.id = base.deserialize.read_integer ();
					break;
				case 1:
					this.name = base.deserialize.read_string ();
					break;
				case 2:
					this.count = base.deserialize.read_integer ();
					break;
				default:
					base.deserialize.read_unknow_data ();
					break;
				}
			}
		}

		public override int encode (SprotoStream stream) {
			base.serialize.open (stream);

			if (base.has_field.has_field (0)) {
				base.serialize.write_integer (this.id, 0);
			}

			if (base.has_field.has_field (1)) {
				base.serialize.write_string (this.name, 1);
			}

			if (base.has_field.has_field (2)) {
				base.serialize.write_integer (this.count, 2);
			}

			return base.serialize.close ();
		}
	}


}


namespace serverprotoProtocol{ 
	public class drop : SprotoProtocolBase {
		public const int tag = 2;
		public override int GetTag() {
			return tag;
		}

		public serverprotoType.drop.request request;


		static drop () {
			ProtocolFunctionDictionary.SetRequest<serverprotoType.drop.request> (tag);
		}


		public override SprotoTypeBase GetRequest() {
			return this.request;
		}

		public override SprotoTypeBase GetResponse() {
			return null;
		}
	}

	public class sysmessage : SprotoProtocolBase {
		public const int tag = 1;
		public override int GetTag() {
			return tag;
		}

		public serverprotoType.sysmessage.request request;


		static sysmessage () {
			ProtocolFunctionDictionary.SetRequest<serverprotoType.sysmessage.request> (tag);
		}


		public override SprotoTypeBase GetRequest() {
			return this.request;
		}

		public override SprotoTypeBase GetResponse() {
			return null;
		}
	}

}

